version: "2.0"
services:
  web:
    image: mbed/pelion-quick-start-web-app:latest
    ports:
      - "5000:5000"
    depends_on:
      - db
    links:
      - db
    environment:
      DATABASE_URL: postgres://postgres:example@db:5432/postgres
    env_file:
      - docker.env
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
