version: "2.0"
services:
  web:
    image: mbed/pelion-quick-start-web-app:latest
    ports:
      - "5000:5000"
    depends_on:
      - db
    links:
      - db
    environment:
      DATABASE_URL: postgres://postgres:example@db:5432/postgres
      API_KEY: ${API_KEY}
      API_HOST: ${API_HOST}
      DEVICE_ID: ${DEVICE_ID}
      RESOURCE: ${RESOURCE}
      LONG_POLLING_ENABLED: ${LONG_POLLING_ENABLED}
  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
